services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 2g
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  imgproxy:
    image: darthsim/imgproxy:latest
    container_name: imgproxy
    restart: always
    environment:
      IMGPROXY_BIND: ":8080"
      IMGPROXY_KEY: ""
      IMGPROXY_SALT: ""
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: "/images"
    ports:
      - "8082:8080"
    volumes:
      - ${LOCAL_IMAGES_DIR}:/images:ro
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: always
    environment:
      MEILI_NO_ANALYTICS: "true"      # 关闭匿名统计
      # MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}   # 设置主密钥（必须自己填）
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
volumes:
  postgres_data:
  meili_data: