// This file is auto-generated by @hey-api/openapi-ts

export const DatasetTreeSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        children: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/DatasetTree'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Children'
        }
    },
    type: 'object',
    required: ['id', 'name', 'children'],
    title: 'DatasetTree'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImageOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        raw_size_image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Size Image Url'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        size: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ImageSize'
                },
                {
                    type: 'null'
                }
            ]
        },
        score_quality: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Score Quality'
        },
        score_aesthetics: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Score Aesthetics'
        }
    },
    type: 'object',
    required: ['id', 'path', 'url', 'raw_size_image_url', 'title', 'tags', 'size', 'score_quality', 'score_aesthetics'],
    title: 'ImageOut'
} as const;

export const ImageRequestSchema = {
    properties: {
        ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Ids'
        },
        page: {
            type: 'integer',
            title: 'Page',
            default: 0
        },
        pageSize: {
            type: 'integer',
            title: 'Pagesize',
            default: 20
        }
    },
    type: 'object',
    required: ['ids'],
    title: 'ImageRequest'
} as const;

export const ImageSizeSchema = {
    properties: {
        w: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'W'
        },
        h: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'H'
        }
    },
    type: 'object',
    required: ['w', 'h'],
    title: 'ImageSize'
} as const;

export const ImagesOutSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        images: {
            items: {
                '$ref': '#/components/schemas/ImageOut'
            },
            type: 'array',
            title: 'Images'
        }
    },
    type: 'object',
    required: ['total', 'images'],
    title: 'ImagesOut'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;