// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetDatasetTreeApiDatasetsTreeGetData, GetDatasetTreeApiDatasetsTreeGetResponses, GetImagesApiImagesPostData, GetImagesApiImagesPostResponses, GetImagesApiImagesPostErrors } from './types.gen';
import { getDatasetTreeApiDatasetsTreeGetResponseTransformer } from './transformers.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Dataset Tree
 */
export const getDatasetTreeApiDatasetsTreeGet = <ThrowOnError extends boolean = false>(options?: Options<GetDatasetTreeApiDatasetsTreeGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDatasetTreeApiDatasetsTreeGetResponses, unknown, ThrowOnError>({
        responseTransformer: getDatasetTreeApiDatasetsTreeGetResponseTransformer,
        url: '/api/datasets/tree',
        ...options
    });
};

/**
 * Get Images
 */
export const getImagesApiImagesPost = <ThrowOnError extends boolean = false>(options: Options<GetImagesApiImagesPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GetImagesApiImagesPostResponses, GetImagesApiImagesPostErrors, ThrowOnError>({
        url: '/api/images',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};