// This file is auto-generated by @hey-api/openapi-ts

import type { GetDatasetTreeApiDatasetsTreeGetResponse } from './types.gen';

const datasetTreeSchemaResponseTransformer = (data: any) => {
    if (data.children) {
        data.children = data.children.map((item: any) => {
            return datasetTreeSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getDatasetTreeApiDatasetsTreeGetResponseTransformer = async (data: any): Promise<GetDatasetTreeApiDatasetsTreeGetResponse> => {
    data = data.map((item: any) => {
        return datasetTreeSchemaResponseTransformer(item);
    });
    return data;
};