// This file is auto-generated by @hey-api/openapi-ts

/**
 * DatasetTree
 */
export type DatasetTree = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Children
     */
    children: Array<DatasetTree> | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageOut
 */
export type ImageOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Path
     */
    path: string;
    /**
     * Url
     */
    url: string | null;
    /**
     * Raw Size Image Url
     */
    raw_size_image_url: string | null;
    /**
     * Title
     */
    title: string | null;
    /**
     * Tags
     */
    tags: Array<string> | null;
    size: ImageSize | null;
    /**
     * Score Quality
     */
    score_quality: number | null;
    /**
     * Score Aesthetics
     */
    score_aesthetics: number | null;
};

/**
 * ImageRequest
 */
export type ImageRequest = {
    /**
     * Ids
     */
    ids: Array<string>;
    /**
     * Page
     */
    page?: number;
    /**
     * Pagesize
     */
    pageSize?: number;
};

/**
 * ImageSize
 */
export type ImageSize = {
    /**
     * W
     */
    w: number | null;
    /**
     * H
     */
    h: number | null;
};

/**
 * ImagesOut
 */
export type ImagesOut = {
    /**
     * Total
     */
    total: number;
    /**
     * Images
     */
    images: Array<ImageOut>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetDatasetTreeApiDatasetsTreeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/datasets/tree';
};

export type GetDatasetTreeApiDatasetsTreeGetResponses = {
    /**
     * Response Get Dataset Tree Api Datasets Tree Get
     * Successful Response
     */
    200: Array<DatasetTree>;
};

export type GetDatasetTreeApiDatasetsTreeGetResponse = GetDatasetTreeApiDatasetsTreeGetResponses[keyof GetDatasetTreeApiDatasetsTreeGetResponses];

export type GetImagesApiImagesPostData = {
    body: ImageRequest;
    path?: never;
    query?: never;
    url: '/api/images';
};

export type GetImagesApiImagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetImagesApiImagesPostError = GetImagesApiImagesPostErrors[keyof GetImagesApiImagesPostErrors];

export type GetImagesApiImagesPostResponses = {
    /**
     * Successful Response
     */
    200: ImagesOut;
};

export type GetImagesApiImagesPostResponse = GetImagesApiImagesPostResponses[keyof GetImagesApiImagesPostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};